spring:
  application:
    name: catalog-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-catalog:5432/catalogdb}
    username: ${SPRING_DATASOURCE_USERNAME:catalog_user}
    password: ${SPRING_DATASOURCE_PASSWORD:catalog_pass}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: catalog-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}