spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-payment:5432/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:payment_user}
    password: ${SPRING_DATASOURCE_PASSWORD:payment_pass}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8083

payment:
  simulation:
    failure-rate: ${PAYMENT_FAILURE_RATE:0.30}
    min-latency-ms: 200
    max-latency-ms: 800

resilience4j:
  circuitbreaker:
    instances:
      orderService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true

feign:
  circuitbreaker:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: payment-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
